# **Tipos de Tensores**

In [ ]:
import torch

In [ ]:
lista = [[1,2,3],
         [4,5,6]]

In [ ]:
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [ ]:
tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)

torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)


In [ ]:
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


# **Outras formas de instanciar Tensores**

In [ ]:
import numpy as np

In [ ]:
arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)

print(tns)
print(tns.dtype)

[[0.50273083 0.48110698 0.43852215 0.39809848]
 [0.16790767 0.34903989 0.65977236 0.88469268]
 [0.2692439  0.04495397 0.49449251 0.13431811]]
float64
tensor([[0.5027, 0.4811, 0.4385, 0.3981],
        [0.1679, 0.3490, 0.6598, 0.8847],
        [0.2692, 0.0450, 0.4945, 0.1343]], dtype=torch.float64)
torch.float64


In [ ]:
## ele preserva o tipo original dos dados

# **Tensores inicializados**

Essas funções recebem como parâmetro o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:

* torch.one() -> Cria um tensor preenchido com zeros.
* torch.zeros() -> Cria um tensor preenchido com uns.
* torch.randn() -> Cria um tensor preenchido com números aleatórios a partir de uma distribuição normal

In [ ]:
tns1 = torch.ones(2,3)
tns2 = torch.zeros(4,5)
tns3 = torch.randn(3,3)

print(tns1)
print(tns2)
print(tns3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.3994,  0.5585,  0.1620],
        [ 1.7006, -0.2593, -0.4884],
        [ 1.2520,  0.2152,  2.0159]])


# **Tensor para array numpy**

In [ ]:
arr = tns3.data.numpy()
print(arr)
print(type(arr))

[[ 0.39943686  0.55848646  0.16204494]
 [ 1.7005621  -0.25928283 -0.48840618]
 [ 1.252021    0.21520822  2.0158634 ]]
<class 'numpy.ndarray'>


# **Indexação**

É o mesmo que acessar elementos.

In [ ]:
print(tns3)

tensor([[ 0.3994,  0.5585,  0.1620],
        [ 1.7006, -0.2593, -0.4884],
        [ 1.2520,  0.2152,  2.0159]])


In [ ]:
tns3[0,2] = -10
print(tns3)

tensor([[  0.3994,   0.5585, -10.0000],
        [  1.7006,  -0.2593,  -0.4884],
        [  1.2520,   0.2152,   2.0159]])


In [ ]:
print(tns3[0:2])
## Acessar parte do tensor

tensor([[  0.3994,   0.5585, -10.0000],
        [  1.7006,  -0.2593,  -0.4884]])


In [ ]:
print(tns3[0,2])

tensor(-10.)


**# Operações com Tensores**

A função .item() utilizada anteriormente extrai o número de um tensor que possui um único valor, permitindo realizar as oprações numéricas do Python. Caso não seja extraído,operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas **ponto a ponto**, operando cada elemento (i, j) do tensor t1, com o elemento (i, j) do tensor t2.

In [ ]:
tns = tns3[0:2, :]
# pegando uma parte, para que possa ficar no mesmo tamanho do outro tensor que vamos utilizar

In [ ]:
print(tns.shape)
print(tns1.shape)

torch.Size([2, 3])
torch.Size([2, 3])


In [ ]:
print(tns)
print(tns1)
print(tns+tns1)

tensor([[  0.3994,   0.5585, -10.0000],
        [  1.7006,  -0.2593,  -0.4884]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 1.3994,  1.5585, -9.0000],
        [ 2.7006,  0.7407,  0.5116]])


In [ ]:
print(tns)
print(tns1)
print(tns*tns1)

tensor([[  0.3994,   0.5585, -10.0000],
        [  1.7006,  -0.2593,  -0.4884]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[  0.3994,   0.5585, -10.0000],
        [  1.7006,  -0.2593,  -0.4884]])


In [ ]:
print(tns)
print(tns1)
print(tns/tns1)

tensor([[  0.3994,   0.5585, -10.0000],
        [  1.7006,  -0.2593,  -0.4884]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[  0.3994,   0.5585, -10.0000],
        [  1.7006,  -0.2593,  -0.4884]])


In [ ]:
## Concatenar = função cat
tns1 = torch.ones(2,3)
tns2 = torch.zeros(2,3)
tns_out = torch.cat( (tns1, tns2), dim=0 )
print(tns_out)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])


# **Função s.size() e view()**

In [ ]:
print(tns1.size())

torch.Size([2, 3])


In [ ]:
tns4 = torch.randn(2,2,3)
print(tns4)
## Esse tensor é como se fosse um cubo

tensor([[[ 0.3439, -0.9199,  1.0848],
         [ 0.2539,  1.1898,  1.0909]],

        [[-2.0175, -1.4007, -0.3526],
         [ 0.8914,  1.6440,  0.4765]]])


In [ ]:
## Para eu "achatar" o tensor
tns4 = tns4.view(12)
print(tns4)

tensor([ 0.3439, -0.9199,  1.0848,  0.2539,  1.1898,  1.0909, -2.0175, -1.4007,
        -0.3526,  0.8914,  1.6440,  0.4765])


In [ ]:
tns4 = tns4.view(4, 3)
print(tns4)

tensor([[ 0.3439, -0.9199,  1.0848],
        [ 0.2539,  1.1898,  1.0909],
        [-2.0175, -1.4007, -0.3526],
        [ 0.8914,  1.6440,  0.4765]])


In [ ]:
## Qundo eu não sei a dimensão do meu tensor (muito comum no dia-a-dia)
## O -1 tb é usado para "achatar"

tns4 = tns4.view(tns4.size(0), -1)
print(tns4)

tensor([[ 0.3439, -0.9199,  1.0848],
        [ 0.2539,  1.1898,  1.0909],
        [-2.0175, -1.4007, -0.3526],
        [ 0.8914,  1.6440,  0.4765]])


# **GPU Cast**

Para que o seu script dê suporte a infraestruturas com e sem GPU, é importante o dispositivo no início do seu código estar de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisarmos subir valores na GPU, como os pesos da rede, os gradientes e etc

In [ ]:
## Primeiro precisa verificar de a GPU está disponível

if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

cpu


In [ ]:
## Caso eu queira jogar na GPU, preciso importar novamente o torch e mudar as configurações para a GPU 
## (Editar - Configurações do Notebook - Hardware accelerator GPU - Save)

import torch

tns5 = torch.randn(10)
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')
print(device)

tns5 = tns5.to(device)
print(tns5)



cuda
tensor([-1.0597, -1.2580, -0.1869,  0.6412, -0.7464, -1.2536,  0.8345,  0.0733,
         0.7087,  0.2429], device='cuda:0')


# **Exercícios**

In [ ]:
import torch
tns = torch.randn(9, 12)
tns1 = tns[0:5, 0:4]
tns2 = tns[5:, 4:]

resultado = torch.mm(tns1, tns2)
print(resultado.size())

torch.Size([5, 8])


In [ ]:
import torch 
tns1 = torch.randn(7,7,3)
tns2 = torch.randn(147, 1)

tns1 = tns1.view(-1, 1)
soma = tns1 + tns2
print(soma)

tensor([[ 0.5923],
        [-2.4625],
        [-0.0145],
        [ 0.2785],
        [ 1.0574],
        [ 0.9412],
        [-0.0966],
        [-1.0864],
        [ 0.8572],
        [ 0.9451],
        [-1.0394],
        [ 0.5496],
        [-1.4460],
        [-0.1370],
        [ 2.2054],
        [-0.1318],
        [-2.7226],
        [-0.4098],
        [ 0.0708],
        [ 0.1492],
        [ 1.5960],
        [-0.6942],
        [-1.1043],
        [ 0.4288],
        [ 2.9546],
        [ 1.5330],
        [ 0.6133],
        [ 0.6925],
        [-0.5544],
        [ 0.5920],
        [-0.2571],
        [ 2.5797],
        [ 0.4684],
        [ 0.3700],
        [ 0.3293],
        [ 0.3027],
        [-1.1302],
        [ 1.9699],
        [-0.3250],
        [-1.5669],
        [ 2.7323],
        [ 0.7984],
        [ 1.8808],
        [ 1.6756],
        [ 2.0444],
        [-1.3057],
        [-1.8361],
        [ 1.1063],
        [ 0.4015],
        [-1.2554],
        [-1.9215],
        [-1.4461],
        [-2.